//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.ShortLinksWSPersistence {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueTupleOfInt32String", Namespace="https://slsoft.net/")]
    [System.SerializableAttribute()]
    public partial class ValueTupleOfInt32String : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Item1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Item1 {
            get {
                return this.Item1Field;
            }
            set {
                if ((this.Item1Field.Equals(value) != true)) {
                    this.Item1Field = value;
                    this.RaisePropertyChanged("Item1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Item2 {
            get {
                return this.Item2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item2Field, value) != true)) {
                    this.Item2Field = value;
                    this.RaisePropertyChanged("Item2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://slsoft.net/", ConfigurationName="ShortLinksWSPersistence.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento URLDestino del espacio de nombres https://slsoft.net/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://slsoft.net/GenerarShortLink", ReplyAction="*")]
        Persistence.ShortLinksWSPersistence.GenerarShortLinkResponse GenerarShortLink(Persistence.ShortLinksWSPersistence.GenerarShortLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://slsoft.net/GenerarShortLink", ReplyAction="*")]
        System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.GenerarShortLinkResponse> GenerarShortLinkAsync(Persistence.ShortLinksWSPersistence.GenerarShortLinkRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento URLDestino del espacio de nombres https://slsoft.net/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://slsoft.net/GenerarShortLinkPersonzalizado", ReplyAction="*")]
        Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoResponse GenerarShortLinkPersonzalizado(Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://slsoft.net/GenerarShortLinkPersonzalizado", ReplyAction="*")]
        System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoResponse> GenerarShortLinkPersonzalizadoAsync(Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Mensaje del espacio de nombres https://slsoft.net/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://slsoft.net/EnviarSMS", ReplyAction="*")]
        Persistence.ShortLinksWSPersistence.EnviarSMSResponse EnviarSMS(Persistence.ShortLinksWSPersistence.EnviarSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://slsoft.net/EnviarSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.EnviarSMSResponse> EnviarSMSAsync(Persistence.ShortLinksWSPersistence.EnviarSMSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Serial del espacio de nombres https://slsoft.net/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://slsoft.net/GetLicence", ReplyAction="*")]
        Persistence.ShortLinksWSPersistence.GetLicenceResponse GetLicence(Persistence.ShortLinksWSPersistence.GetLicenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://slsoft.net/GetLicence", ReplyAction="*")]
        System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.GetLicenceResponse> GetLicenceAsync(Persistence.ShortLinksWSPersistence.GetLicenceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarShortLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarShortLink", Namespace="https://slsoft.net/", Order=0)]
        public Persistence.ShortLinksWSPersistence.GenerarShortLinkRequestBody Body;
        
        public GenerarShortLinkRequest() {
        }
        
        public GenerarShortLinkRequest(Persistence.ShortLinksWSPersistence.GenerarShortLinkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://slsoft.net/")]
    public partial class GenerarShortLinkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string URLDestino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Contraseña;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre;
        
        public GenerarShortLinkRequestBody() {
        }
        
        public GenerarShortLinkRequestBody(string URLDestino, string Usuario, string Contraseña, string Nombre) {
            this.URLDestino = URLDestino;
            this.Usuario = Usuario;
            this.Contraseña = Contraseña;
            this.Nombre = Nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarShortLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarShortLinkResponse", Namespace="https://slsoft.net/", Order=0)]
        public Persistence.ShortLinksWSPersistence.GenerarShortLinkResponseBody Body;
        
        public GenerarShortLinkResponse() {
        }
        
        public GenerarShortLinkResponse(Persistence.ShortLinksWSPersistence.GenerarShortLinkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://slsoft.net/")]
    public partial class GenerarShortLinkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Persistence.ShortLinksWSPersistence.ValueTupleOfInt32String GenerarShortLinkResult;
        
        public GenerarShortLinkResponseBody() {
        }
        
        public GenerarShortLinkResponseBody(Persistence.ShortLinksWSPersistence.ValueTupleOfInt32String GenerarShortLinkResult) {
            this.GenerarShortLinkResult = GenerarShortLinkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarShortLinkPersonzalizadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarShortLinkPersonzalizado", Namespace="https://slsoft.net/", Order=0)]
        public Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequestBody Body;
        
        public GenerarShortLinkPersonzalizadoRequest() {
        }
        
        public GenerarShortLinkPersonzalizadoRequest(Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://slsoft.net/")]
    public partial class GenerarShortLinkPersonzalizadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string URLDestino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Contraseña;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NombrePersonalizado;
        
        public GenerarShortLinkPersonzalizadoRequestBody() {
        }
        
        public GenerarShortLinkPersonzalizadoRequestBody(string URLDestino, string Usuario, string Contraseña, string NombrePersonalizado) {
            this.URLDestino = URLDestino;
            this.Usuario = Usuario;
            this.Contraseña = Contraseña;
            this.NombrePersonalizado = NombrePersonalizado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarShortLinkPersonzalizadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarShortLinkPersonzalizadoResponse", Namespace="https://slsoft.net/", Order=0)]
        public Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoResponseBody Body;
        
        public GenerarShortLinkPersonzalizadoResponse() {
        }
        
        public GenerarShortLinkPersonzalizadoResponse(Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://slsoft.net/")]
    public partial class GenerarShortLinkPersonzalizadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Persistence.ShortLinksWSPersistence.ValueTupleOfInt32String GenerarShortLinkPersonzalizadoResult;
        
        public GenerarShortLinkPersonzalizadoResponseBody() {
        }
        
        public GenerarShortLinkPersonzalizadoResponseBody(Persistence.ShortLinksWSPersistence.ValueTupleOfInt32String GenerarShortLinkPersonzalizadoResult) {
            this.GenerarShortLinkPersonzalizadoResult = GenerarShortLinkPersonzalizadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarSMS", Namespace="https://slsoft.net/", Order=0)]
        public Persistence.ShortLinksWSPersistence.EnviarSMSRequestBody Body;
        
        public EnviarSMSRequest() {
        }
        
        public EnviarSMSRequest(Persistence.ShortLinksWSPersistence.EnviarSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://slsoft.net/")]
    public partial class EnviarSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Contraseña;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Destino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Nombre;
        
        public EnviarSMSRequestBody() {
        }
        
        public EnviarSMSRequestBody(string Mensaje, string Usuario, string Contraseña, string Destino, string Nombre) {
            this.Mensaje = Mensaje;
            this.Usuario = Usuario;
            this.Contraseña = Contraseña;
            this.Destino = Destino;
            this.Nombre = Nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarSMSResponse", Namespace="https://slsoft.net/", Order=0)]
        public Persistence.ShortLinksWSPersistence.EnviarSMSResponseBody Body;
        
        public EnviarSMSResponse() {
        }
        
        public EnviarSMSResponse(Persistence.ShortLinksWSPersistence.EnviarSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://slsoft.net/")]
    public partial class EnviarSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Persistence.ShortLinksWSPersistence.ValueTupleOfInt32String EnviarSMSResult;
        
        public EnviarSMSResponseBody() {
        }
        
        public EnviarSMSResponseBody(Persistence.ShortLinksWSPersistence.ValueTupleOfInt32String EnviarSMSResult) {
            this.EnviarSMSResult = EnviarSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLicenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLicence", Namespace="https://slsoft.net/", Order=0)]
        public Persistence.ShortLinksWSPersistence.GetLicenceRequestBody Body;
        
        public GetLicenceRequest() {
        }
        
        public GetLicenceRequest(Persistence.ShortLinksWSPersistence.GetLicenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://slsoft.net/")]
    public partial class GetLicenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Serial;
        
        public GetLicenceRequestBody() {
        }
        
        public GetLicenceRequestBody(string Serial) {
            this.Serial = Serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLicenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLicenceResponse", Namespace="https://slsoft.net/", Order=0)]
        public Persistence.ShortLinksWSPersistence.GetLicenceResponseBody Body;
        
        public GetLicenceResponse() {
        }
        
        public GetLicenceResponse(Persistence.ShortLinksWSPersistence.GetLicenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://slsoft.net/")]
    public partial class GetLicenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLicenceResult;
        
        public GetLicenceResponseBody() {
        }
        
        public GetLicenceResponseBody(string GetLicenceResult) {
            this.GetLicenceResult = GetLicenceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Persistence.ShortLinksWSPersistence.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Persistence.ShortLinksWSPersistence.WebServiceSoap>, Persistence.ShortLinksWSPersistence.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Persistence.ShortLinksWSPersistence.GenerarShortLinkResponse Persistence.ShortLinksWSPersistence.WebServiceSoap.GenerarShortLink(Persistence.ShortLinksWSPersistence.GenerarShortLinkRequest request) {
            return base.Channel.GenerarShortLink(request);
        }
        
        public Persistence.ShortLinksWSPersistence.ValueTupleOfInt32String GenerarShortLink(string URLDestino, string Usuario, string Contraseña, string Nombre) {
            Persistence.ShortLinksWSPersistence.GenerarShortLinkRequest inValue = new Persistence.ShortLinksWSPersistence.GenerarShortLinkRequest();
            inValue.Body = new Persistence.ShortLinksWSPersistence.GenerarShortLinkRequestBody();
            inValue.Body.URLDestino = URLDestino;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contraseña = Contraseña;
            inValue.Body.Nombre = Nombre;
            Persistence.ShortLinksWSPersistence.GenerarShortLinkResponse retVal = ((Persistence.ShortLinksWSPersistence.WebServiceSoap)(this)).GenerarShortLink(inValue);
            return retVal.Body.GenerarShortLinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.GenerarShortLinkResponse> Persistence.ShortLinksWSPersistence.WebServiceSoap.GenerarShortLinkAsync(Persistence.ShortLinksWSPersistence.GenerarShortLinkRequest request) {
            return base.Channel.GenerarShortLinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.GenerarShortLinkResponse> GenerarShortLinkAsync(string URLDestino, string Usuario, string Contraseña, string Nombre) {
            Persistence.ShortLinksWSPersistence.GenerarShortLinkRequest inValue = new Persistence.ShortLinksWSPersistence.GenerarShortLinkRequest();
            inValue.Body = new Persistence.ShortLinksWSPersistence.GenerarShortLinkRequestBody();
            inValue.Body.URLDestino = URLDestino;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contraseña = Contraseña;
            inValue.Body.Nombre = Nombre;
            return ((Persistence.ShortLinksWSPersistence.WebServiceSoap)(this)).GenerarShortLinkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoResponse Persistence.ShortLinksWSPersistence.WebServiceSoap.GenerarShortLinkPersonzalizado(Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequest request) {
            return base.Channel.GenerarShortLinkPersonzalizado(request);
        }
        
        public Persistence.ShortLinksWSPersistence.ValueTupleOfInt32String GenerarShortLinkPersonzalizado(string URLDestino, string Usuario, string Contraseña, string NombrePersonalizado) {
            Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequest inValue = new Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequest();
            inValue.Body = new Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequestBody();
            inValue.Body.URLDestino = URLDestino;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contraseña = Contraseña;
            inValue.Body.NombrePersonalizado = NombrePersonalizado;
            Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoResponse retVal = ((Persistence.ShortLinksWSPersistence.WebServiceSoap)(this)).GenerarShortLinkPersonzalizado(inValue);
            return retVal.Body.GenerarShortLinkPersonzalizadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoResponse> Persistence.ShortLinksWSPersistence.WebServiceSoap.GenerarShortLinkPersonzalizadoAsync(Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequest request) {
            return base.Channel.GenerarShortLinkPersonzalizadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoResponse> GenerarShortLinkPersonzalizadoAsync(string URLDestino, string Usuario, string Contraseña, string NombrePersonalizado) {
            Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequest inValue = new Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequest();
            inValue.Body = new Persistence.ShortLinksWSPersistence.GenerarShortLinkPersonzalizadoRequestBody();
            inValue.Body.URLDestino = URLDestino;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contraseña = Contraseña;
            inValue.Body.NombrePersonalizado = NombrePersonalizado;
            return ((Persistence.ShortLinksWSPersistence.WebServiceSoap)(this)).GenerarShortLinkPersonzalizadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Persistence.ShortLinksWSPersistence.EnviarSMSResponse Persistence.ShortLinksWSPersistence.WebServiceSoap.EnviarSMS(Persistence.ShortLinksWSPersistence.EnviarSMSRequest request) {
            return base.Channel.EnviarSMS(request);
        }
        
        public Persistence.ShortLinksWSPersistence.ValueTupleOfInt32String EnviarSMS(string Mensaje, string Usuario, string Contraseña, string Destino, string Nombre) {
            Persistence.ShortLinksWSPersistence.EnviarSMSRequest inValue = new Persistence.ShortLinksWSPersistence.EnviarSMSRequest();
            inValue.Body = new Persistence.ShortLinksWSPersistence.EnviarSMSRequestBody();
            inValue.Body.Mensaje = Mensaje;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contraseña = Contraseña;
            inValue.Body.Destino = Destino;
            inValue.Body.Nombre = Nombre;
            Persistence.ShortLinksWSPersistence.EnviarSMSResponse retVal = ((Persistence.ShortLinksWSPersistence.WebServiceSoap)(this)).EnviarSMS(inValue);
            return retVal.Body.EnviarSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.EnviarSMSResponse> Persistence.ShortLinksWSPersistence.WebServiceSoap.EnviarSMSAsync(Persistence.ShortLinksWSPersistence.EnviarSMSRequest request) {
            return base.Channel.EnviarSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.EnviarSMSResponse> EnviarSMSAsync(string Mensaje, string Usuario, string Contraseña, string Destino, string Nombre) {
            Persistence.ShortLinksWSPersistence.EnviarSMSRequest inValue = new Persistence.ShortLinksWSPersistence.EnviarSMSRequest();
            inValue.Body = new Persistence.ShortLinksWSPersistence.EnviarSMSRequestBody();
            inValue.Body.Mensaje = Mensaje;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contraseña = Contraseña;
            inValue.Body.Destino = Destino;
            inValue.Body.Nombre = Nombre;
            return ((Persistence.ShortLinksWSPersistence.WebServiceSoap)(this)).EnviarSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Persistence.ShortLinksWSPersistence.GetLicenceResponse Persistence.ShortLinksWSPersistence.WebServiceSoap.GetLicence(Persistence.ShortLinksWSPersistence.GetLicenceRequest request) {
            return base.Channel.GetLicence(request);
        }
        
        public string GetLicence(string Serial) {
            Persistence.ShortLinksWSPersistence.GetLicenceRequest inValue = new Persistence.ShortLinksWSPersistence.GetLicenceRequest();
            inValue.Body = new Persistence.ShortLinksWSPersistence.GetLicenceRequestBody();
            inValue.Body.Serial = Serial;
            Persistence.ShortLinksWSPersistence.GetLicenceResponse retVal = ((Persistence.ShortLinksWSPersistence.WebServiceSoap)(this)).GetLicence(inValue);
            return retVal.Body.GetLicenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.GetLicenceResponse> Persistence.ShortLinksWSPersistence.WebServiceSoap.GetLicenceAsync(Persistence.ShortLinksWSPersistence.GetLicenceRequest request) {
            return base.Channel.GetLicenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Persistence.ShortLinksWSPersistence.GetLicenceResponse> GetLicenceAsync(string Serial) {
            Persistence.ShortLinksWSPersistence.GetLicenceRequest inValue = new Persistence.ShortLinksWSPersistence.GetLicenceRequest();
            inValue.Body = new Persistence.ShortLinksWSPersistence.GetLicenceRequestBody();
            inValue.Body.Serial = Serial;
            return ((Persistence.ShortLinksWSPersistence.WebServiceSoap)(this)).GetLicenceAsync(inValue);
        }
    }
}
