using System;

namespace Domain.CXN
{
    public class CXN_HCTF
    {
        public int HC_Adm { get; set; }
        public string HC_Pac { get; set; }
        public int HC_PacId { get; set; }
        public int HC_Ase { get; set; }
        public int HC_Cia { get; set; }
        public int HC_Prof { get; set; }
        public DateTime HC_FechaNto { get; set; }
        public string HC_Edad { get; set; }
        public string HC_EstadoC { get; set; }
        public string HC_Hijos { get; set; }
        public string HC_Estudios { get; set; }
        public string HC_Dx { get; set; }
        public string HC_TiempoE { get; set; }
        public string HC_TratamientosP { get; set; }
        public string HC_ExaDiag { get; set; }
        public string HC_Ocupacion { get; set; }
        public string HC_MotivoCons { get; set; }
        public string HC_AntFam { get; set; }
        public string HC_CIE10 { get; set; }
        public string HC_AntPat { get; set; }
        public string HC_AntNeu { get; set; }
        public string HC_SalMen { get; set; }
        public string HC_OsteoMusc { get; set; }
        public string HC_Endocrino { get; set; }
        public string HC_Quir { get; set; }
        public string HC_Resp { get; set; }
        public string HC_Derma { get; set; }
        public string HC_Farma { get; set; }
        public string HC_DolorEIAN { get; set; }
        public string HC_Eva { get; set; }
        public string HC_FrecDol { get; set; }
        public string HC_TipoDol { get; set; }
        public string HC_CaracDol { get; set; }
        public string HC_SensiDol { get; set; }
        public string HC_SintAso { get; set; }
        public string HC_HabTox { get; set; }
        public string HC_ActFis { get; set; }
        public string HC_MedExt { get; set; }
        public string HC_Cual1 { get; set; }
        public string HC_Cual2 { get; set; }
        public int HC_Cant { get; set; }
        public string HC_CC1 { get; set; }
        public string HC_CC2 { get; set; }
        public string HC_CC3 { get; set; }
        public string HC_CC4 { get; set; }
        public string HC_CC5 { get; set; }
        public string HC_CC6 { get; set; }
        public string HC_CD1 { get; set; }
        public string HC_CD2 { get; set; }
        public string HC_CD3 { get; set; }
        public string HC_CD4 { get; set; }
        public string HC_H1 { get; set; }
        public string HC_H2 { get; set; }
        public string HC_H3 { get; set; }
        public string HC_H4 { get; set; }
        public string HC_H5 { get; set; }
        public string HC_H6 { get; set; }
        public string HC_C1 { get; set; }
        public string HC_C2 { get; set; }
        public string HC_C3 { get; set; }
        public string HC_C4 { get; set; }
        public string HC_C5 { get; set; }
        public string HC_C6 { get; set; }
        public string HC_T1 { get; set; }
        public string HC_T2 { get; set; }
        public string HC_T3 { get; set; }
        public string HC_T4 { get; set; }
        public string HC_T5 { get; set; }
        public string HC_T6 { get; set; }
        public string HC_T7 { get; set; }
        public string HC_T8 { get; set; }
        public string HC_T9 { get; set; }
        public string HC_T10 { get; set; }
        public string HC_T11 { get; set; }
        public string HC_T12 { get; set; }
        public string HC_T13 { get; set; }
        public string HC_T14 { get; set; }
        public string HisExtCuI { get; set; }
        public string HisExtCuD { get; set; }
        public string HisEscalenosI { get; set; }
        public string HisEscalenosD { get; set; }
        public string HisTrapSupI { get; set; }
        public string HisTrapSupD { get; set; }
        public string HisTrapMedI { get; set; }
        public string HisTrapMedD { get; set; }
        public string HisTrapInfI { get; set; }
        public string HisTrapInfD { get; set; }
        public string HisSerAntI { get; set; }
        public string HisSerAntD { get; set; }
        public string HisPecMayI { get; set; }
        public string HisPecMayD { get; set; }
        public string HisRomI { get; set; }
        public string HisRomD { get; set; }
        public string HisAbSupI { get; set; }
        public string HisAbSupD { get; set; }
        public string HisAbdInfI { get; set; }
        public string HisAbdInfD { get; set; }
        public string HisOblicuoI { get; set; }
        public string HisOblicuoD { get; set; }
        public string HisExtDorsalI { get; set; }
        public string HisExtDorsalD { get; set; }
        public string HisExtLumbarI { get; set; }
        public string HisExtLumbarD { get; set; }
        public string HisGluMayI { get; set; }
        public string HisGluMayD { get; set; }
        public string HisGluMedI { get; set; }
        public string HisGluMedD { get; set; }
        public string HisCuadriI { get; set; }
        public string HisCuadriD { get; set; }
        public string HisIsquiI { get; set; }
        public string HisIsquiD { get; set; }
        public string HisGemeloI { get; set; }
        public string HisGemeloD { get; set; }
        public string HisTibAntI { get; set; }
        public string HisTibAntD { get; set; }
        public string HisEscaAntI { get; set; }
        public string HisEscaAntD { get; set; }
        public string HisEscaMedI { get; set; }
        public string HisEscaMedD { get; set; }
        public string HisEscaPosI { get; set; }
        public string HisEscaPosD { get; set; }
        public string HisECMI { get; set; }
        public string HisECMD { get; set; }
        public string HisCualLumI { get; set; }
        public string HisCualLumD { get; set; }
        public string HisCuadI { get; set; }
        public string HisCuadD { get; set; }
        public string HisIsquiI2 { get; set; }
        public string HisIsqui2D { get; set; }
        public string HisTensorI { get; set; }
        public string HisTensorD { get; set; }
        public string HisGastroI { get; set; }
        public string HisGastroD { get; set; }
        public string HisTAquilesI { get; set; }
        public string HisTAquilesD { get; set; }
        public string HisCabeza { get; set; }
        public string HisHombros { get; set; }
        public string HisBrazos { get; set; }
        public string HisCadera { get; set; }
        public string HisRodilla { get; set; }
        public string HisRotula { get; set; }
        public string HisTibia { get; set; }
        public string HisTobillo { get; set; }
        public string HisPie { get; set; }
        public string HisCuello { get; set; }
        public string HisEspaldaA { get; set; }
        public string HisTorax { get; set; }
        public string HisAbdomen { get; set; }
        public string HisEspaldaB { get; set; }
        public string HisPelvis { get; set; }
        public string HisRodillas { get; set; }
        public string HisEscapula { get; set; }
        public string HisColumna { get; set; }
        public string HisCrestasIliacas { get; set; }
        public string HisGluteos { get; set; }
        public string HisFosa { get; set; }
        public string HisDiagnostico { get; set; }
        public string HisPronostico { get; set; }
        public string HisAcciones { get; set; }
        public string HisConducta { get; set; }
        public DateTime HC_Fecha { get; set; }
        public string Marcha_Mec { get; set; }
        public string HC_Text60 { get; set; }
        public string TipoHistoria { get; set; }
        public int HC_Id { get; set; }
    }
}
