using System;

namespace Domain.CXN
{
    public class CXN_HCTO
    {
        public int HC_Adm { get; set; }
        public string HC_Pac { get; set; }
        public int HC_PacId { get; set; }
        public int HC_Ase { get; set; }
        public int HC_Cia { get; set; }
        public int HC_Prof { get; set; }
        public DateTime HC_Fecha { get; set; }
        public string HC_Edad { get; set; }
        public int HC_Cant { get; set; }
        public DateTime HC_FechaNto { get; set; }
        public string HC_NotaAcl { get; set; }
        public string HC_CIE10 { get; set; }
        public string HC_DiagMedico { get; set; }
        public string HC_OcuAct { get; set; }
        public string HC_HisFam { get; set; }
        public string HC_HisOcu { get; set; }
        public string HC_HabRut { get; set; }
        public string HC_DiagOcu { get; set; }
        public string HC_Acciones { get; set; }
        public string HC_AntLaboral { get; set; }
        public string MSD_MCP { get; set; }
        public string MSD_MCA { get; set; }
        public string MSD_MBP { get; set; }
        public string MSD_MBA { get; set; }
        public string MSD_MHP { get; set; }
        public string MSD_MHA { get; set; }
        public string MSD_MEP { get; set; }
        public string MSD_MEA { get; set; }
        public string MSD_MCIP { get; set; }
        public string MSD_MCIA { get; set; }
        public string MSD_MPP { get; set; }
        public string MSD_MPA { get; set; }
        public string MSD_MRP { get; set; }
        public string MSD_MRA { get; set; }
        public string MSD_MPIEP { get; set; }
        public string MSD_MPIEA { get; set; }
        public string MSI_MCP { get; set; }
        public string MSI_MCA { get; set; }
        public string MSI_MBP { get; set; }
        public string MSI_MBA { get; set; }
        public string MSI_MHP { get; set; }
        public string MSI_MHA { get; set; }
        public string MSI_MEP { get; set; }
        public string MSI_MEA { get; set; }
        public string MSI_MCIP { get; set; }
        public string MSI_MCIA { get; set; }
        public string MSI_MPP { get; set; }
        public string MSI_MPA { get; set; }
        public string MSI_MRP { get; set; }
        public string MSI_MRA { get; set; }
        public string MSI_MPIEP { get; set; }
        public string MSI_MPIEA { get; set; }
        public string MSD_AAP { get; set; }
        public string MSD_AAA { get; set; }
        public string MSD_AABP { get; set; }
        public string MSD_AABA { get; set; }
        public string MSD_AADP { get; set; }
        public string MSD_AADA { get; set; }
        public string MSD_AATP { get; set; }
        public string MSD_AATA { get; set; }
        public string MSD_AALP { get; set; }
        public string MSD_AALA { get; set; }
        public string MSD_AGAP { get; set; }
        public string MSD_AGAA { get; set; }
        public string MSD_AGACILP { get; set; }
        public string MSD_AGACILA { get; set; }
        public string MSD_AGAESFP { get; set; }
        public string MSD_AGAESFA { get; set; }
        public string MSD_PINFP { get; set; }
        public string MSD_PINFA { get; set; }
        public string MSD_PINTP { get; set; }
        public string MSD_PINTA { get; set; }
        public string MSD_PLATP { get; set; }
        public string MSD_PLATA { get; set; }
        public string MSI_AAP { get; set; }
        public string MSI_AAA { get; set; }
        public string MSI_AABP { get; set; }
        public string MSI_AABA { get; set; }
        public string MSI_AADP { get; set; }
        public string MSI_AADA { get; set; }
        public string MSI_AATP { get; set; }
        public string MSI_AATA { get; set; }
        public string MSI_AALP { get; set; }
        public string MSI_AALA { get; set; }
        public string MSI_AGAP { get; set; }
        public string MSI_AGAA { get; set; }
        public string MSI_AGACILP { get; set; }
        public string MSI_AGACILA { get; set; }
        public string MSI_AGAESFP { get; set; }
        public string MSI_AGAESFA { get; set; }
        public string MSI_PINFP { get; set; }
        public string MSI_PINFA { get; set; }
        public string MSI_PINTP { get; set; }
        public string MSI_PINTA { get; set; }
        public string MSI_PLATP { get; set; }
        public string MSI_PLATA { get; set; }
        public string HC_ObservaFMS { get; set; }
        public string HC_A_C1 { get; set; }
        public string HC_A_C2 { get; set; }
        public string HC_A_C3 { get; set; }
        public string HC_A_C4 { get; set; }
        public string HC_A_C5 { get; set; }
        public string HC_A_C6 { get; set; }
        public string HC_A_C7 { get; set; }
        public string HC_A_C8 { get; set; }
        public string HC_A_C9 { get; set; }
        public string HC_A_C10 { get; set; }
        public string HC_A_C11 { get; set; }
        public string HC_A_C12 { get; set; }
        public string HC_A_C13 { get; set; }
        public string HC_A_C14 { get; set; }
        public string HC_A_C15 { get; set; }
        public string HC_A_C16 { get; set; }
        public string HC_A_C17 { get; set; }
        public string HC_A_C18 { get; set; }
        public string HC_A_C19 { get; set; }
        public string HC_A_C20 { get; set; }
        public string HC_A_C21 { get; set; }
        public string HC_A_C22 { get; set; }
        public string HC_A_C23 { get; set; }
        public string HC_A_C24 { get; set; }
        public string HC_A_C25 { get; set; }
        public string HC_A_C26 { get; set; }
        public string HC_A_C27 { get; set; }
        public string HC_A_C28 { get; set; }
        public string HC_A_C29 { get; set; }
        public string HC_A_T1 { get; set; }
        public string HC_A_T2 { get; set; }
        public string HC_A_T3 { get; set; }
        public string HC_A_T4 { get; set; }
        public string HC_A_T5 { get; set; }
        public string HC_A_T6 { get; set; }
        public string HC_A_T7 { get; set; }
        public string HC_A_T8 { get; set; }
        public string HC_A_T9 { get; set; }
        public string HC_A_T10 { get; set; }
        public string HC_A_T11 { get; set; }
        public string HC_A_T12 { get; set; }
        public string HC_A_T13 { get; set; }
        public string HC_A_T14 { get; set; }
        public string HC_A_T15 { get; set; }
        public string HC_A_T16 { get; set; }
        public string HC_A_T17 { get; set; }
        public string HC_A_T18 { get; set; }
        public string HC_A_T19 { get; set; }
        public string HC_A_T20 { get; set; }
        public string HC_A_T21 { get; set; }
        public string HC_A_T22 { get; set; }
        public string HC_A_T23 { get; set; }
        public string HC_A_T24 { get; set; }
        public string HC_A_T25 { get; set; }
        public string HC_A_T26 { get; set; }
        public string HC_A_T27 { get; set; }
        public string HC_A_T28 { get; set; }
        public string HC_A_T29 { get; set; }
        public string HC_A_T30 { get; set; }
        public string HC_A_T31 { get; set; }
        public string HC_A_T32 { get; set; }
        public string HC_A_T33 { get; set; }
        public string HC_A_T34 { get; set; }
        public string HC_A_T35 { get; set; }
        public string HC_A_ObservaVD { get; set; }
        public string HC_A_T37 { get; set; }
        public string HC_A_T38 { get; set; }
        public string HC_A_T39 { get; set; }
        public string HC_A_T40 { get; set; }
        public string HC_A_T41 { get; set; }
        public string HC_A_T42 { get; set; }
        public string HC_A_T43 { get; set; }
        public string HC_A_T44 { get; set; }
        public string HC_A_T45 { get; set; }
        public string HC_A_T46 { get; set; }
        public string HC_A_T47 { get; set; }
        public string HC_A_T48 { get; set; }
        public string HC_A_ObservaH { get; set; }
        public string HC_A_T50 { get; set; }
        public string HC_A_T51 { get; set; }
        public string HC_A_T52 { get; set; }
        public string HC_A_T53 { get; set; }
        public string HC_A_T54 { get; set; }
        public string HC_A_T55 { get; set; }
        public string HC_A_T56 { get; set; }
        public string HC_A_T57 { get; set; }
        public string HC_A_T58 { get; set; }
        public string HC_A_T59 { get; set; }
        public string HC_A_T60 { get; set; }
        public string HC_A_ObservaAVD { get; set; }
        public string HC_PronoOcu { get; set; }
        public int HC_Id { get; set; }
    }
}
