using System;

namespace Domain.Fibromialgia
{
    public class ClaseReportsFibro : DatosTF
    {
        public string Name { get; set; }
        public DateTime Fecha1 { get; set; }
        public DateTime Fecha2 { get; set; }
        public DateTime Fecha3 { get; set; }
        public DateTime Fecha4 { get; set; }
        public DateTime Fecha5 { get; set; }
        public string Dato1 { get; set; }
        public string Dato2 { get; set; }
        public string Dato3 { get; set; }
        public string Dato4 { get; set; }
        public string Dato5 { get; set; }
        public string Dato6 { get; set; }
        public string Dato7 { get; set; }
        public string Dato8 { get; set; }
        public string Dato9 { get; set; }
        public string Dato10 { get; set; }
        public string Dato11 { get; set; }
        public string Dato12 { get; set; }
        public string Dato13 { get; set; }
        public string Dato14 { get; set; }
        public string Dato15 { get; set; }
        public string Dato16 { get; set; }
        public string Dato17 { get; set; }
        public string Dato18 { get; set; }
        public string Dato19 { get; set; }
        public string Dato20 { get; set; }
        public string Dato21 { get; set; }
        public string Dato22 { get; set; }
        public string Dato23 { get; set; }
        public string Dato24 { get; set; }
        public string Dato25 { get; set; }
        public string Dato26 { get; set; }
        public string Dato27 { get; set; }
        public string Dato28 { get; set; }
        public string Dato29 { get; set; }
        public string Dato30 { get; set; }
        public string Dato31 { get; set; }
        public string Dato32 { get; set; }
        public string Dato33 { get; set; }
        public string Dato34 { get; set; }
        public string Dato35 { get; set; }
        public string Dato36 { get; set; }
        public string Dato37 { get; set; }
        public string Dato38 { get; set; }
        public string Dato39 { get; set; }
        public string Dato40 { get; set; }
        public string Dato41 { get; set; }
        public string Dato42 { get; set; }
        public string Dato43 { get; set; }
        public string Dato44 { get; set; }
        public string Dato45 { get; set; }
        public string Dato46 { get; set; }
        public string Dato47 { get; set; }
        public string Dato48 { get; set; }
        public string Dato49 { get; set; }
        public string Dato50 { get; set; }
        public string Dato51 { get; set; }
        public string Dato52 { get; set; }
        public string Dato53 { get; set; }
        public string Dato54 { get; set; }
        public string Dato55 { get; set; }
        public string Dato56 { get; set; }
        public string Dato57 { get; set; }
        public string Dato58 { get; set; }
        public string Dato59 { get; set; }
        public string Dato60 { get; set; }
        public string Dato61 { get; set; }
        public string Dato62 { get; set; }
        public string Dato63 { get; set; }
        public string Dato64 { get; set; }
        public string Dato65 { get; set; }
        public string Dato66 { get; set; }
        public string Dato67 { get; set; }
        public string Dato68 { get; set; }
        public string Dato69 { get; set; }
        public string Dato70 { get; set; }
        public string Dato71 { get; set; }
        public string Dato72 { get; set; }
        public string Dato73 { get; set; }
        public string Dato74 { get; set; }
        public string Dato75 { get; set; }
        public string Dato76 { get; set; }
        public string Dato77 { get; set; }
        public string Dato78 { get; set; }
        public string Dato79 { get; set; }
        public string Dato80 { get; set; }
        public string Dato81 { get; set; }
        public string Dato82 { get; set; }
        public string Dato83 { get; set; }
        public string Dato84 { get; set; }
        public string Dato85 { get; set; }
        public string Dato86 { get; set; }
        public string Dato87 { get; set; }
        public string Dato88 { get; set; }
        public string Dato89 { get; set; }
        public string Dato90 { get; set; }
        public string Dato91 { get; set; }
        public string Dato92 { get; set; }
        public string Dato93 { get; set; }
        public string Dato94 { get; set; }
        public string Dato95 { get; set; }
        public string Dato96 { get; set; }
        public string Dato97 { get; set; }
        public string Dato98 { get; set; }
        public string Dato99 { get; set; }
        public string Dato100 { get; set; }
        public string Dato101 { get; set; }
        public string Dato102 { get; set; }
        public string Dato103 { get; set; }
        public string Dato104 { get; set; }
        public string Dato105 { get; set; }
        public string Dato106 { get; set; }
        public string Dato107 { get; set; }
        public string Dato108 { get; set; }
        public string Dato109 { get; set; }
    }
    public class DatosTF
    {
        public byte[] Graph { get; set; }
        public int EAV { get; set; }
        public string Cervical_HC_CC1 { get; set; }
        public string Cervical_HC_CC2 { get; set; }
        public string Cervical_HC_CC3 { get; set; }
        public string Cervical_HC_CC4 { get; set; }
        public string Cervical_HC_CC5 { get; set; }
        public string Cervical_HC_CC6 { get; set; }

        public string Cervical_HC_CD1 { get; set; }
        public string Cervical_HC_CD2 { get; set; }
        public string Cervical_HC_CD3 { get; set; }
        public string Cervical_HC_CD4 { get; set; }

        public string Hombro_HC_H1 { get; set; }
        public string Hombro_HC_H2 { get; set; }
        public string Hombro_HC_H3 { get; set; }
        public string Hombro_HC_H4 { get; set; }
        public string Hombro_HC_H5 { get; set; }
        public string Hombro_HC_H6 { get; set; }

        public string Cadera_HC_C1 { get; set; }
        public string Cadera_HC_C2 { get; set; }
        public string Cadera_HC_C3 { get; set; }
        public string Cadera_HC_C4 { get; set; }
        public string Cadera_HC_C5 { get; set; }
        public string Cadera_HC_C6 { get; set; }

        public string Codo_HC_T1 { get; set; }
        public string Codo_HC_T2 { get; set; }

        public string Rodilla_HC_T3 { get; set; }
        public string Rodilla_HC_T4 { get; set; }

        public string Antebrazo_HC_T5 { get; set; }
        public string Antebrazo_HC_T6 { get; set; }

        public string Tobillo_HC_T7 { get; set; }
        public string Tobillo_HC_T8 { get; set; }
        public string Tobillo_HC_T9 { get; set; }
        public string Tobillo_HC_T10 { get; set; }

        public string RadioCarpiana_HC_T11 { get; set; }
        public string RadioCarpiana_HC_T12 { get; set; }
        public string RadioCarpiana_HC_T13 { get; set; }
        public string RadioCarpiana_HC_T14 { get; set; }

        //Table 3
        public string HisExtCui { get; set; }
        public string HisExtCuD { get; set; }
        public string HisEscalenosI { get; set; }
        public string HisEscalenosD { get; set; }
        public string HisTrapSupI { get; set; }
        public string HisTrapSupD { get; set; }
        public string HisTrapMedI { get; set; }
        public string HisTrapMedD { get; set; }
        public string HisTrapInfI { get; set; }
        public string HisTrapInfD { get; set; }
        public string HisSerAntI { get; set; }
        public string HisSerAntD { get; set; }
        public string HisPecMayI { get; set; }
        public string HisPecMayD { get; set; }
        public string HisRomI { get; set; }
        public string HisRomD { get; set; }
        public string HisAbSupI { get; set; }
        public string HisAbSupD { get; set; }
        public string HisAbdInfI { get; set; }
        public string HisAbdInfD { get; set; }
        public string HisOblicuoI { get; set; }
        public string HisOblicuoD { get; set; }
        public string HisExtDorsalI { get; set; }
        public string HisExtDorsalD { get; set; }
        public string HisExtLumbarI { get; set; }
        public string HisExtLumbarD { get; set; }
        public string HisGluMayI { get; set; }
        public string HisGluMayD { get; set; }
        public string HisGluMedI { get; set; }
        public string HisGluMedD { get; set; }
        public string HisCuadriI { get; set; }
        public string HisCuadriD { get; set; }
        public string HisIsquiI { get; set; }
        public string HisIsquiD { get; set; }
        public string HisGemeloI { get; set; }
        public string HisGemeloD { get; set; }
        public string HisTibAntI { get; set; }
        public string HisTibAntD { get; set; }

        //TABLA 4
        public string HisEscaAntI { get; set; }
        public string HisEscaAntD { get; set; }
        public string HisEscaMedI { get; set; }
        public string HisEscaMedD { get; set; }
        public string HisEscaPosI { get; set; }
        public string HisEscaPosD { get; set; }
        public string HisECMI { get; set; }
        public string HisECMD { get; set; }
        public string HisCualLumI { get; set; }
        public string HisCualLumD { get; set; }
        public string HisCuadI { get; set; }
        public string HisCuadD { get; set; }
        public string HisIsquiI2 { get; set; }
        public string HisIsqui2D { get; set; }
        public string HisTensorI { get; set; }
        public string HisTensorD { get; set; }
        public string HisGastroI { get; set; }
        public string HisGastroD { get; set; }
        public string HisTAquilesI { get; set; }
        public string HisTAquilesD { get; set; }
        public string Dato110 { get; set; }
        public string Dato111 { get; set; }
        public string Dato112 { get; set; }
        public string Dato113 { get; set; }
        public string Dato114 { get; set; }
        public string Dato115 { get; set; }
        public string Dato116 { get; set; }
        public string Dato117 { get; set; }
        public string Dato118 { get; set; }
        public string Dato119 { get; set; }
        public string Dato120 { get; set; }
        public string Dato121 { get; set; }
        public string Dato122 { get; set; }
        public string Dato123 { get; set; }
        public string Dato124 { get; set; }
        public string Dato125 { get; set; }
        public string Dato126 { get; set; }
        public string Dato127 { get; set; }
        public string Dato128 { get; set; }
        public string Dato129 { get; set; }
        public string Dato130 { get; set; }
        public string Dato131 { get; set; }
        public string Dato132 { get; set; }
        public string Dato133 { get; set; }
        public string Dato134 { get; set; }
        public string Dato135 { get; set; }
        public string Dato136 { get; set; }
        public string Dato137 { get; set; }
        public string Dato138 { get; set; }
        public string Dato139 { get; set; }
        public string Dato140 { get; set; }
        public string Dato141 { get; set; }
        public string Dato142 { get; set; }
        public string Dato143 { get; set; }
        public string Dato144 { get; set; }
        public string Dato145 { get; set; }
        public string Dato146 { get; set; }
        public string Dato147 { get; set; }
        public string Dato148 { get; set; }
        public string Dato149 { get; set; }
        public string Dato150 { get; set; }
        public string Dato151 { get; set; }
        public string Dato152 { get; set; }
        public string Dato153 { get; set; }
        public string Dato154 { get; set; }
        public string Dato155 { get; set; }
        public string Dato156 { get; set; }
        public string Dato157 { get; set; }
        public string Dato158 { get; set; }
        public string Dato159 { get; set; }
        public string Dato160 { get; set; }
        public string Dato161 { get; set; }


        public string Dato162 { get; set; }
        public string Dato163 { get; set; }
        public string Dato164 { get; set; }
        public string Dato165 { get; set; }
        public string Dato166 { get; set; }
        public string Dato167 { get; set; }
        public string Dato168 { get; set; }
        public string Dato169 { get; set; }
        public string Dato170 { get; set; }
        public string Dato171 { get; set; }
        public string Dato172 { get; set; }
        public string Dato173 { get; set; }
        public string Dato174 { get; set; }
        public string Dato175 { get; set; }
        public string Dato176 { get; set; }
        public string Dato177 { get; set; }
        public string Dato178 { get; set; }
        public string Dato179 { get; set; }
        public string Dato180 { get; set; }
        public string Dato181 { get; set; }
        public string Dato182 { get; set; }
        public string Dato183 { get; set; }
        public string Dato184 { get; set; }
        public string Dato185 { get; set; }
        public string Dato186 { get; set; }
        public string Dato187 { get; set; }
        public string Dato188 { get; set; }
        public string Dato189 { get; set; }
        public string Dato190 { get; set; }
        public string Dato191 { get; set; }
        public string Dato192 { get; set; }
        public string Dato193 { get; set; }
        public string Dato194 { get; set; }
        public string Dato195 { get; set; }
        public string Dato196 { get; set; }


        public string Dato197 { get; set; }
        public string Dato198 { get; set; }
        public string Dato199 { get; set; }
        public string Dato200 { get; set; }
        public string Dato201 { get; set; }
        public string Dato202 { get; set; }
        public string Dato203 { get; set; }
        public string Dato204 { get; set; }
        public string Dato205 { get; set; }
        public string Dato206 { get; set; }
        public string Dato207 { get; set; }
        public string Dato208 { get; set; }
        public string Dato209 { get; set; }
        public string Dato210 { get; set; }
        public string Dato211 { get; set; }
        public string Dato212 { get; set; }
        public string Dato213 { get; set; }
        public string Dato214 { get; set; }
        public string Dato215 { get; set; }
        public string Dato216 { get; set; }
        public string Dato217 { get; set; }
        public string Dato218 { get; set; }
        public string Dato219 { get; set; }
        public string Dato220 { get; set; }
        public string Dato221 { get; set; }
        public string Dato222 { get; set; }
        public string Dato223 { get; set; }
        public string Dato224 { get; set; }
        public string Dato225 { get; set; }
        public string Dato226 { get; set; }
        public string Dato227 { get; set; }
        public string Dato228 { get; set; }
        public string Dato229 { get; set; }
        public string Dato230 { get; set; }
        public string Dato231 { get; set; }
        public string Dato232 { get; set; }
        public string Dato233 { get; set; }
        public string Dato234 { get; set; }
        public string Dato235 { get; set; }
        public string Dato236 { get; set; }
        public string Dato237 { get; set; }
        public string Dato238 { get; set; }
        public string Dato239 { get; set; }
        public string Dato240 { get; set; }
        public string Dato241 { get; set; }
        public string Dato242 { get; set; }
        public string Dato243 { get; set; }
        public string Dato244 { get; set; }
        public string Dato245 { get; set; }
        public string Dato246 { get; set; }
        public string Dato247 { get; set; }
        public string Dato248 { get; set; }
        public string Dato249 { get; set; }
        public string Dato250 { get; set; }
        public string Dato251 { get; set; }
        public string Dato252 { get; set; }
        public string Dato253 { get; set; }
        public string Dato254 { get; set; }
        public string Dato255 { get; set; }
        public string Dato256 { get; set; }
        public string Dato257 { get; set; }
        public string Dato258 { get; set; }
        public string Dato259 { get; set; }
        public string Dato260 { get; set; }
        public string Dato261 { get; set; }
        public string Dato262 { get; set; }
        public string Dato263 { get; set; }
        public string Dato264 { get; set; }
        public string Dato265 { get; set; }
        public string Dato266 { get; set; }
        public string Dato267 { get; set; }
        public string Dato268 { get; set; }
        public string Dato269 { get; set; }
        public string Dato270 { get; set; }
        public string Dato271 { get; set; }
        public string Dato272 { get; set; }
        public string Dato273 { get; set; }
        public string Dato274 { get; set; }
        public string Dato275 { get; set; }
        public string Dato276 { get; set; }
        public string Dato277 { get; set; }
        public string Dato278 { get; set; }
        public string Dato279 { get; set; }
        public string Dato280 { get; set; }
        public string Dato281 { get; set; }
        public string Dato282 { get; set; }
        public string Dato283 { get; set; }
        public int Admision { get; set; }

    }

    public class DatosForInforme
    {
        public string TID { get; set; }
        public string IDD { get; set; }
        public DateTime Desde { get; set; }
        public DateTime Hasta { get; set; }
        public string Name { get; set; }
    }

    public class Paciente
    {
        public int PacId { get; set; }
        public string Nombre { get; set; }
    }
    public class E1Respuestas
    {
        public double FIQ1 { get; set; }
        public double D1111 { get; set; }
        public double D1121 { get; set; }
        public double D1131 { get; set; }
        public double D1141 { get; set; }
        public double D1151 { get; set; }
        public double D1161 { get; set; }
        public double D1171 { get; set; }
        public double D1181 { get; set; }
        public double Promedio81 { get; set; }
        public double promedioEmocional1 { get; set; }
        public double promedioFisico1 { get; set; }

        public double FIQ2 { get; set; }
        public double D1112 { get; set; }
        public double D1122 { get; set; }
        public double D1132 { get; set; }
        public double D1142 { get; set; }
        public double D1152 { get; set; }
        public double D1162 { get; set; }
        public double D1172 { get; set; }
        public double D1182 { get; set; }
        public double Promedio82 { get; set; }
        public double promedioEmocional2 { get; set; }
        public double promedioFisico2 { get; set; }

        public int idPaciente { get; set; }
        public string paciente { get; set; }

        public DateTime Desde { get; set; }
        public DateTime Hasta { get; set; }
        public byte[] Logo { get; set; }
    }
    public class CSF36_1
    {
        public int ListaPosision { get; set; }
        public string Rango { get; set; }
        public string Cuestionario { get; set; }
        public string Indicador { get; set; }
        public double FIQ1 { get; set; }
        public double D1111 { get; set; }
        public double D1121 { get; set; }
        public double D1131 { get; set; }
        public double D1141 { get; set; }
        public double D1151 { get; set; }
        public double D1161 { get; set; }
        public double D1171 { get; set; }
        public double D1181 { get; set; }
        public double Promedio81 { get; set; }
        public double promedioEmocional1 { get; set; }
        public double promedioFisico1 { get; set; }
        public double FIQ2 { get; set; }
        public double D1112 { get; set; }
        public double D1122 { get; set; }
        public double D1132 { get; set; }
        public double D1142 { get; set; }
        public double D1152 { get; set; }
        public double D1162 { get; set; }
        public double D1172 { get; set; }
        public double D1182 { get; set; }
        public double Promedio82 { get; set; }
        public double promedioEmocional2 { get; set; }
        public double promedioFisico2 { get; set; }
        public int IdPac { get; set; }
        public string paciente { get; set; }
        public double ResultadoFIQTotal { get; set; }
        public int NumAplicaciones { get; set; }
        public DateTime Desde { get; set; }
        public DateTime Hasta { get; set; }
        public byte[] Logo { get; set; }
    }
    public class Preguntas3
    {
        public string Pregunta1 { get; set; }
        public string Pregunta2 { get; set; }
        public string Pregunta3 { get; set; }
        public string Pregunta4 { get; set; }
        public string Pregunta5 { get; set; }
        public string Pregunta6 { get; set; }
        public string Pregunta7 { get; set; }
        public string Pregunta8 { get; set; }
        public string Pregunta9 { get; set; }
        public string Pregunta10 { get; set; }
        public byte[] Graph1 { get; set; }
        public byte[] Graph2 { get; set; }
        public byte[] Graph3 { get; set; }
        public byte[] Graph4 { get; set; }
        public byte[] Graph5 { get; set; }
        public byte[] Graph6 { get; set; }
        public byte[] Graph7 { get; set; }
        public byte[] Graph8 { get; set; }
        public byte[] Graph9 { get; set; }
        public byte[] Graph10 { get; set; }
        public DateTime Desde { get; set; }
        public DateTime Hasta { get; set; }
    }
}
